baseURL: "https://ryanpalstra.com/"
languageCode: "en-us"
title: "Ryan Palstra"

module:
  imports:
  - path: "github.com/joshed-io/reveal-hugo"

theme: "github.com/joshed-io/reveal-hugo"

markup:
  goldmark:
    renderer:
      unsafe: true

outputFormats:
  Reveal:
    baseName: "index"
    mediaType: "text/html"
    isHTML: true
